### ISSUE TITLE
Improve image loading/performance

### ISSUE THREAD

**Issue by danielbergholz** [danielbergholz/techschool.dev#55]
Let's be honest, it's HORRIBLE when you visit a page and there is a bunch of images flashing on the screen after they load, and that's precisely what happens on TechSchool today. We need to find a more performant way of loading the images or maybe show some "loading skeleton" on the image while it loads (this could be a new component for image, that is reused on the entire website)

**Comment by dmitry-sidorov** [comment]
@danielbergholz Hey, I can take this one!

**Comment by dmitry-sidorov** [comment]
Images for courses are loading faster without lazy loading! It's almost impossible without throttling to figure out "adopt liveview" loaded latter, than the others.
 
With lazy loading 
[lazy_loading 2.zip](https://github.com/user-attachments/files/15865420/lazy_loading.2.zip)

Without lazy loading
[without_lazy_loading 2.zip](https://github.com/user-attachments/files/15865428/without_lazy_loading.2.zip)

Looks like with lazy loading images are waiting until the biggest ("adopt liveview") finishes loading. 

Images for courses (youtube videos) are loading blazing fast. I think, this is possible because of Google CDN, which gives fast speed for the most places around the world. (magic link https://i.ytimg.com)

Now I am looking for a way to hook the moment, when image ends loading and show it instead of loader/skeleton. It might be useful for low connection speed (see loading with throttling).

**Comment by danielbergholz** [comment]
Super interesting! Thanks for the insights! I'll assign this issue to you then, feel free to ask any other questions here.
And feel free to remove the lazy loading for the courses images 🤝

**Comment by danielbergholz** [comment]
I fixed this by using inline SVGs instead of an `img` tag. This way the icon is already rendered when the page loads and it reduces the load on the server to serve multiple images.

See commit https://github.com/danielbergholz/techschool.dev/commit/f8ebe995b101379402e5e6af5bc3acae9a4d51f9
